### ISSUE TITLE
Do you have any hyperparameter tuning suggestions to make MoE-OFA better performance in the image caption stage1 fine-tuning?

### ISSUE THREAD

**Issue by dannyxiaocn** [OFA-Sys/OFA#111]
Hi! Same as the subject.

**Comment by yangapku** [comment]
Hi, before tuning the downstream performance, I would suggest to first make some sanity checks on the implementation of MoE model, which may include:
+ weights of MoE FFN params on different experts should be randomly initialized with different values (if not restored from pretrained OFA FFN weights)
+ grads of the expert params (given with a `.expert` attribute in the code) should not be all-reduced, since they are not shared across experts
+ the total grad norms on different workers should be the same (considering the grads of the expert params are not all-reduced), otherwise the clipped grad of shared parameters will be different on different workers
+ the save and restore of expert / shared param weights & optimizer states are all working correctly
