### ISSUE TITLE
Hugging Face Model Can't Download

### ISSUE THREAD

**Issue by c-liangyu** [OFA-Sys/OFA#167]
OFA-huge model cannot be downloaded. Authentication error.

By the way, may I know why the pre-trained model weight on Hugging Face (OFA-Huge 3GB+) is much smaller than the official checkpoints (OFA-Huge 10GB+)?

pytorch_model.bin · OFA-Sys/OFA-huge at main
https://huggingface.co/OFA-Sys/OFA-huge/blob/main/pytorch_model.bin

**Comment by JustinLin610** [comment]
Sorry for my late response. I think it is due to the access limitation. See if you can download now, as I have just disabled it. 

The size difference comes from the existence of optimizer states. As we provide FP32 parameters, the official checkpoint should be around 3 times (weight + optimizer states) larger than the huggingface one (only weight).
