### ISSUE TITLE
NCLL error when evaluation on VQA

### ISSUE THREAD

**Issue by zd11024** [OFA-Sys/OFA#248]
Hi, now I try to evaluate my custom datasets (which are extremely large) with vqa_large_best.pt. When the evaluate.py is about to end, the program raises `RuntimeError: NCLL error in xxxx, unhandled cuda error, NCCL version 2.10.3`. The cuda version is 11.3, and the pytorch is of 1.12.1+cu113. Note that the error does not come out when the dataset is relatively small, and the training process is OK.  Have you ever met similar mistakes?
<img width="881" alt="image" src="https://user-images.githubusercontent.com/34681526/192098277-1c601274-3988-4876-b008-1a7961743466.png">

**Comment by yangapku** [comment]
Hi, actually we have met this error before, maybe due to the too large amount of communication data between GPU workers to merge the results. You can try to skip this communication step by commenting the corresponding line in `evaluate.py` and save the results into individual splits (in the format of JSON files) for each GPU. Then you can merge them manually into a complete result file.

**Comment by zd11024** [comment]
Many thanks! I will try to merge these results manually.
