### ISSUE TITLE
what's the hardware requirement?

### ISSUE THREAD

**Issue by WukongZeming** [OFA-Sys/OFA#41]
both for training and for generating, do you have the recommondent?
many thx!

**Comment by dannyxiaocn** [comment]
From what I have seen, 4 GPU with 24GB memory ( NVIDIA 3090 ) will have a not bad effect with smaller batch_size and higher update_freq in image_caption, snli, and glue experiments. However, my other GPU like NVIDIA 2080 with 12 GB memory is actually not quite suitable for these tests, because only loading the checkpoints will take several GB.

**Comment by yangapku** [comment]
Thanks a lot! @dannyxiaocn For OFA-large, we performed our experiments mostly on (single or multiple) servers with V100-32GB GPUs. For GPUs with less memory, please try to use smaller `batch_size` and increase `update_freq` (refer to this issue proposed by dannyxiao #27 ).

**Comment by yangapku** [comment]
Meanwhile, if the GPU memory is still not enough, you can also try OFA-base or change to a smaller image resolution during finetuning by modifying `--patch-image-size` to a smaller value like 384.

**Comment by WukongZeming** [comment]
thanks a lot for all you guys!!
