### ISSUE TITLE
Visualization of the image token

### ISSUE THREAD

**Issue by Richar-Du** [OFA-Sys/OFA#58]
Thanks for your awesome work! I wonder how could I get the patch pixels of an image token? I know it requires the dVAE decoder
to decode the image tokens. Does the code contain the decoding process? Or could you recommend any pre-trained models that I could quickly decode the image tokens? I appreciate your reply.

**Comment by jxst539246** [comment]
We use the [VQGAN](https://github.com/CompVis/taming-transformers) instead of the dVAE as the image tokenizer in our model.  Our released code contains the decoding process (and the encoding process in the future).

The pretrained ckpt we use is an f8-model with 8192 codebook entries
![image](https://user-images.githubusercontent.com/17763236/160318394-a487a9ae-88ed-4722-818e-059fd9b76d3e.png). We also add this pretrained VQGAN ckpt to our text-to-image ckpt zip file. 

As for visualization, from our previous experience, it doesn't make much sense to visualize a single image token from VQGAN codebooks. The image tokens will influence each other during the decoding process.
